workflows:
  ios-app:
    name: ProtoApp iOS Build
    max_build_duration: 60
    environment:
      groups:
        - A
      xcode: latest
      vars:
        PROJECT_DIR: ProtoApp
        XCODE_PROJECT: ProtoApp.xcodeproj
        XCODE_SCHEME: ProtoApp
    scripts:
      - name: Resolve Swift package dependencies
        script: |
          set -euo pipefail
          cd "$PROJECT_DIR"
          xcodebuild -resolvePackageDependencies -project "$XCODE_PROJECT"
      - name: Build iOS archive
        script: |
          set -euo pipefail
          cd "$PROJECT_DIR"
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            -archivePath "$CM_BUILD_DIR/ProtoApp.xcarchive" \
            clean archive
    artifacts:
      - $CM_BUILD_DIR/ProtoApp.xcarchive
    publishing:
      email:
        recipients:
          - $CM_MAIL
